language: python
sudo: required
python:
  - 3.5
  - 3.6
before_install:
  - sudo apt-get install libyaml-dev
install:
  - python setup.py install
  - pip install codecov
  - pip install localstack
  - localstack start &
script:
  - python setup.py test
after_success:
  - codecov
deploy:
  provider: pypi
  user: guyingbo
  password:
    secure: FhTtvkp8wAkT0dTqRP54a3IVJuYJqtfm5R5MCkGSZaM2dSWiPzdyxq/g15JUYghjGoyAKImTLVRpiGKuBoUQwZLafKJVqxn3Cs8ynghp/LQdPXU1aZsM3YtOodKN1giCP3y1z7C8HGmRLC1i2h/4n+kZyuZZNtrOpAbXtjO0KCiGM0ckdSSLABeuVDLKH01srR8SViXXihc4ecMHAWs1fTOsCirPX284wBpq88Um48ue0YRl9jPhuzdlv5YPHSE0ou7dYaf31X1kSTIyc7/cNFq/JH49Zt4d4WLdk8sKUmiE3u75ss9suicKFz1u5Aepo6uIKRXSm+EkPTOIMYoYPJomSPR58EI2JSK+UZ0IH4Oa30IqVFWSkoa7uQkxCQlOnXKyobctBn65GTph6oEoyFJntEwpYCf2KNQJTyiIU/o6lwrInhmCOAc7XdXffm7i63wRX4zQF5NNIoa8klt0u3MncSsn6c18wZybwNUlUYCwBrcVTc9h7e20yqo2c5zjsvb7iV4PrCSfJD0XEe0h5RKcLamn0XUZnKd7cBQyZBtWzvC/K+ma/zlIrB2cDafZhIn/TuiN+qdEYuD5VLzITyfq5rtDt6NbV3iJF32sGfHO2hRODVi+phkPP19o80wgJBh+HNkE55ICeXk+qajJfCr0dlVqssYkgypgQprrUww=
  on:
    tags: true
